language: android
android:
  components:
  - platform-tools
  - build-tools-21.1.1
  - android-20
install:
- curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
- echo 'deb https://deb.nodesource.com/node precise main' | sudo tee /etc/apt/sources.list.d/nodesource.list > /dev/null
- sudo apt-get -y update
- sudo apt-get -y install nodejs
- sudo npm -g install cordova
- sudo npm install
- npm start
script:
- npm run build
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "install"
  acl: public_read
  on:
    repo: mozilla/webmaker-app-cordova
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "platforms/android/ant-build"
  upload-dir: "dev/android"
  acl: public_read
  on:
    repo: mozilla/webmaker-app-cordova
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "platforms/firefoxos/build"
  upload-dir: "dev/firefoxos"
  acl: public_read
  on:
    repo: mozilla/webmaker-app-cordova
    branch: master
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "platforms/android/ant-build"
  upload-dir: "staging/android"
  acl: public_read
  on:
    all_branches: true
    tags: true
    repo: mozilla/webmaker-app-cordova
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "platforms/firefoxos/build"
  upload-dir: "staging/firefoxos"
  acl: public_read
  on:
    all_branches: true
    tags: true
    repo: mozilla/webmaker-app-cordova
