language: android
env:
  matrix:
    - PLATFORM=android
    - PLATFORM=firefoxos
android:
  components:
  - platform-tools
  - build-tools-21.1.1
  - android-20
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get update -y
- sudo apt-get install -y nodejs
- sudo npm -g install cordova
- sudo npm install
script:
- echo "Script stage"
- npm build
- if [[ $PLATFORM = 'android' ]]; then npm run android:build; fi
- if [[ $PLATFORM = 'firefoxos' ]]; then npm run firefoxos; fi
before_deploy:
- if [[ $PLATFORM = 'android' ]]; then ls "platforms/android/ant-build"; fi
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "platforms/android/ant-build"
  upload-dir: "dev/android"
  acl: public_read
  on:
    repo: mozilla/webmaker-app-cordova
    branch: master
    condition: $PLATFORM = android
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ7GSK4A6OFIMBDGQ
  secret_access_key:
    secure: I7rhqX1vAwimCneD47gjKu+60zUs7KOPndh2nu56RXepP66XtF3AHJZfhaVB6wyTTCO6ZrAukJ4qh6yS5HLfY9w/M/TcXWrCl5wwA/4UT9+VE5DBQ57PwQBYpN+DAtgknzXq/e7uo6tNBXdKu3B4QfWU43+xeC7R2btiYeT0Seo=
  bucket: webmaker-dist
  local-dir: "platforms/firefoxos/build"
  upload-dir: "dev/firefoxos"
  acl: public_read
  on:
    repo: mozilla/webmaker-app-cordova
    branch: master
    condition: $PLATFORM = firefoxos

