language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-20
before_install:
    - echo "Before install stage"
install:
    - echo "Install stage"
    - sudo add-apt-repository -y ppa:chris-lea/node.js
    - sudo apt-get update -y
    - sudo apt-get install -y nodejs
    - sudo npm -g install cordova
before_script:
    - echo "Before script stage"
script:
    - echo "Script stage"
    - cordova build android
after_success:
    - echo "After success stage"
after_failure:
    - echo "After failure stage"
after_script:
    - echo "After script stage"
